# Generated by Django 6.0.3 on 2026-04-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_app_image_url_app_owner_alter_app_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='css_code',
            field=models.TextField(blank=True, default='body { background-color: white; text-align: center; font-family: sans-serif; }', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='html_code',
            field=models.TextField(blank=True, default='<h1>Ku soo dhawaaw App-kayga</h1>', null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='js_code',
            field=models.TextField(blank=True, default="console.log('App-ka waa diyaar!');", null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
