# Generated by Django 6.0.3 on 2026-04-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_app_css_code_app_html_code_app_js_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
