# Generated by Django 6.0.3 on 2026-04-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('message', models.TextField(default='Website-ka waxaa ku socda horumarin, fadlan dib u soo laabo.')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
