# Generated by Django 6.0.3 on 2026-04-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cinwaanka')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sharaxaad kooban')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Sawirka (Ads/Hero)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='YouTube Embed Link')),
                ('button_text', models.CharField(default='Bilow Hadda', max_length=50, verbose_name='Qoraalka Badhanka')),
                ('is_active', models.BooleanField(default=True, verbose_name='Muuqaalka (Active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
