# Generated by Django 6.0.3 on 2026-04-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homepagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'verbose_name': 'Homepage Content', 'verbose_name_plural': 'Homepage Contents'},
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='button_text',
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Sharaxaad'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Sawirka'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Cinwaanka'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Link'),
        ),
    ]
