# Generated by Django 6.0.3 on 2026-04-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_homepagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name="Su'aasha Codbixinta")),
                ('option1', models.CharField(max_length=100, verbose_name='Xubinta 1')),
                ('option2', models.CharField(max_length=100, verbose_name='Xubinta 2')),
                ('votes1', models.IntegerField(default=0, verbose_name='Codadka 1')),
                ('votes2', models.IntegerField(default=0, verbose_name='Codadka 2')),
                ('is_active', models.BooleanField(default=True, verbose_name='Waa Firfircoon')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name="Su'aasha")),
                ('option1', models.CharField(max_length=100, verbose_name='Doorashada 1')),
                ('option2', models.CharField(max_length=100, verbose_name='Doorashada 2')),
                ('option3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doorashada 3')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Jawaabta Saxda ah')),
                ('is_active', models.BooleanField(default=True, verbose_name='Waa Firfircoon')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
