# Generated by Django 6.0.3 on 2026-04-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_content_alter_homepagecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3')], help_text='Dooro nambarka option-ka saxda ah', max_length=1),
        ),
    ]
