# Generated by Django 6.0.3 on 2026-04-27 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_quiz_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='option4',
            field=models.CharField(default=1, max_length=255, verbose_name='Doorashada 4aad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(max_length=255, verbose_name='Jawaabta Saxda Ah'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ma firfircoonaa?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(max_length=255, verbose_name='Doorashada 1aad'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(max_length=255, verbose_name='Doorashada 2aad'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(default='', max_length=255, verbose_name='Doorashada 3aad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=500, verbose_name="Su'aasha"),
        ),
    ]
