# Generated by Django 6.0.3 on 2026-04-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
