# Generated by Django 6.0.3 on 2026-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contactmessage_is_read_quiz_points_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, default='app', unique=True),
            preserve_default=False,
        ),
    ]
