# Generated by Django 6.0.3 on 2026-05-10 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='📚', help_text='Emoji-ga maadada', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={},
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='points',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='message',
            field=models.TextField(default='Website-ka waxaa ku socda horumarin.'),
        ),
        migrations.CreateModel(
            name='ExamContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('read', '📖 Akhri (Study Material)'), ('quiz', '🧩 Ciyaar (Quiz/Test)')], default='quiz', max_length=10)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(help_text='Waa in ay la mid noqotaa mid ka mid ah options-ka', max_length=255)),
                ('explanation', models.TextField(blank=True, help_text="Sharaxaadda su'aasha (Read Mode)", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.examyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.subject')),
            ],
            options={
                'verbose_name': 'Bankiga Imtixaanka',
                'verbose_name_plural': 'Bankiga Imtixaanka',
            },
        ),
    ]
