# Generated by Django 6.0.3 on 2026-05-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_examyear_subject_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examyear',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='examcontent',
            name='reading_text',
            field=models.TextField(blank=True, help_text='Halkan ku qor casharka haddii ay akhris tahay', null=True, verbose_name='Qoraalka Akhriska'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='content_type',
            field=models.CharField(choices=[('akhris', '📖 Akhris kaliya (Reading Mode)'), ('ciyaar', '🎮 Ciyaar/Quiz (Game Mode)')], default='ciyaar', max_length=10, verbose_name='Nooca Xogta'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Waa in ay la mid noqotaa mid ka mid ah options-ka', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='explanation',
            field=models.TextField(blank=True, help_text="Sharaxaad kooban oo ku saabsan su'aasha", null=True, verbose_name='Sharaxaadda'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='option1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Doorashada A'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='option2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Doorashada B'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Doorashada C'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='option4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Doorashada D'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name="Su'aasha"),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.subject', verbose_name='Maaddada'),
        ),
        migrations.AlterField(
            model_name='examcontent',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.examyear', verbose_name='Sannadka'),
        ),
        migrations.AlterField(
            model_name='examyear',
            name='year',
            field=models.IntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], unique=True, verbose_name='Sannadka'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Magaca Maaddada'),
        ),
    ]
