# Generated by Django 6.0.3 on 2026-05-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_examyear_options_examcontent_reading_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcontent',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examcontent',
            name='year',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'verbose_name_plural': 'Homepage Contents'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User Activities'},
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='message',
            field=models.TextField(default='Website-ka waxaa ku socda horumarin, fadlan dib u soo laabo.'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='ExamContent',
        ),
        migrations.DeleteModel(
            name='ExamYear',
        ),
    ]
