# Generated by Django 6.0.3 on 2026-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_examcontent_subject_remove_examcontent_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='image',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/images/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='image_url',
            field=models.URLField(blank=True, help_text='Halkan geli link-ga sawirka haddii uusan computer-kaaga ku jirin', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Calaamadi tan markaad rabto inaad Live gasho'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='live_room_name',
            field=models.CharField(blank=True, help_text='Magaca qolka Live-ka (tusaale: shirka-maanta)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='homepage/videos/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Halkan geli link-ga YouTube ama muuqaal kale', null=True),
        ),
    ]
