# Generated by Django 6.0.3 on 2026-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_homepagecontent_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='live_room_name',
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link-ga sawirka', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link-ga muuqaalka (YouTube/Vimeo)', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='message',
            field=models.TextField(default='Horumarin ayaa socota...'),
        ),
    ]
