# Generated by Django 6.0.3 on 2026-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_homepagecontent_allow_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='body_text',
        ),
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.AddField(
            model_name='content',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link-ga sawirka', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='content/videos/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link-ga muuqaalka (YouTube/Vimeo)', null=True),
        ),
    ]
