# Generated by Django 6.0.3 on 2026-05-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_description_content_body_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_emoji', models.CharField(default='📚', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct_option_index', models.IntegerField(help_text='Geli 0 haddii option1 sax yahay, 1 haddii option2...')),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.examyear')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.examyear')),
            ],
        ),
        migrations.AddField(
            model_name='examyear',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='examyear',
            unique_together={('subject', 'year')},
        ),
    ]
