# Generated by Django 6.0.3 on 2026-05-15 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_examyear_subject_quizquestion_readingmaterial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ciwaanka Ogeysiiska/Xayeysiiska')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Faahfaahinta Qoraalka')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='notices/images/', verbose_name='Soo geli Sawir (File)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Sawir Link ah (URL)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='notices/videos/', verbose_name='Soo geli Muuqaal (File)')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Muuqaal Link ah (URL - YouTube)')),
                ('is_portrait', models.BooleanField(default=False, verbose_name='Muuqaalku ma taagan yahay? (Shorts/TikTok size)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Muu muuqanayaa App-ka? (Active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Notice & Ad',
                'verbose_name_plural': 'Global Notices & Ads',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='icon_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='subject_icons/images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon_image_url',
            field=models.URLField(blank=True, help_text='Link-ga sawirka icon-ka', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon_video_file',
            field=models.FileField(blank=True, null=True, upload_to='subject_icons/videos/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon_video_url',
            field=models.URLField(blank=True, help_text='Link-ga muuqaalka icon-ka', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon_emoji',
            field=models.CharField(blank=True, default='📚', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, db_table='user_profile_friends_map', related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
