# Generated by Django 6.0.3 on 2026-05-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_globalnotice_subject_icon_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='settings/images/', verbose_name='Soo geli Sawir (File)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Sawir Link ah (URL)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='settings/videos/', verbose_name='Soo geli Muuqaal (File)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Muuqaal Link ah (URL)'),
        ),
    ]
