# Generated by Django 6.0.3 on 2026-05-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_sitesetting_image_file_sitesetting_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TTS Global Settings', max_length=100)),
                ('max_characters', models.PositiveIntegerField(default=1000, help_text='Tirada ugu badan ee xarfaha qofku qori karo hal mar.')),
            ],
            options={
                'verbose_name': 'TTS Setting',
                'verbose_name_plural': 'TTS Settings',
            },
        ),
    ]
