# Generated by Django 6.0.3 on 2026-05-16 17:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_ttssetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttssetting',
            name='bg_image_file',
            field=models.ImageField(blank=True, help_text='Soo geli sawirka gadaal uga muuqanaya interface-ka dhalada ah.', null=True, upload_to=core.models.get_upload_path, verbose_name='Sawirka Gadaal (File)'),
        ),
        migrations.AddField(
            model_name='ttssetting',
            name='bg_image_url',
            field=models.URLField(blank=True, help_text='Haddii aad sawirka ka keenayso internet-ka, halkan geli link-giisa.', null=True, verbose_name='Sawirka Gadaal (URL Link)'),
        ),
        migrations.AddField(
            model_name='ttssetting',
            name='bg_video_file',
            field=models.FileField(blank=True, help_text='Soo geli muuqaal (MP4) oo dhabar-ka gadaal uga dagi lahaa interface-ka.', null=True, upload_to=core.models.get_upload_path, verbose_name='Muuqaalka Gadaal (File)'),
        ),
        migrations.AddField(
            model_name='ttssetting',
            name='bg_video_url',
            field=models.URLField(blank=True, help_text='Haddii aad muuqaalka ka keenayso internet-ka, halkan geli link-giisa (MP4 format).', null=True, verbose_name='Muuqaalka Gadaal (URL Link)'),
        ),
        migrations.AddField(
            model_name='ttssetting',
            name='faiza_avatar_image',
            field=models.ImageField(blank=True, help_text='Sawirka rasmiga ah ee goobada ugu muuqanaya Faiza.', null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Sawir)'),
        ),
        migrations.AddField(
            model_name='ttssetting',
            name='faiza_avatar_video',
            field=models.FileField(blank=True, help_text='Haddii aad rabto muuqaal clip ah (MP4) oo goobada gudaheed dhex dhasha.', null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Muuqaal Loop ah)'),
        ),
        migrations.AddField(
            model_name='ttssetting',
            name='maxamed_avatar_image',
            field=models.ImageField(blank=True, help_text='Sawirka rasmiga ah ee goobada ugu muuqanaya Maxamed.', null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Sawir)'),
        ),
        migrations.AddField(
            model_name='ttssetting',
            name='maxamed_avatar_video',
            field=models.FileField(blank=True, help_text='Haddii aad rabto muuqaal clip ah (MP4) oo goobada gudaheed dhex dhasha.', null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Muuqaal Loop ah)'),
        ),
    ]
