# Generated by Django 6.0.3 on 2026-05-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_project_projectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='parent_folder',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
