# Generated by Django 6.0.3 on 2026-05-19 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_temporarylink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('tools', 'Aaladaha (Tools)'), ('games', 'Ciyaaraha (Games)'), ('education', 'Waxbarasho (Education)'), ('business', 'Ganacsi (Business)')], default='tools', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_apps', to=settings.AUTH_USER_MODEL),
        ),
    ]
