# Generated by Django 6.0.3 on 2026-05-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_app_category_app_description_app_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/apk/', verbose_name='Soo geli APK File'),
        ),
        migrations.AddField(
            model_name='app',
            name='exe_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/exe/', verbose_name='Soo geli EXE File'),
        ),
    ]
