# Generated by Django 6.0.3 on 2026-05-19 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_app_apk_file_app_exe_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='apk_file',
        ),
        migrations.RemoveField(
            model_name='app',
            name='category',
        ),
        migrations.RemoveField(
            model_name='app',
            name='description',
        ),
        migrations.RemoveField(
            model_name='app',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='app',
            name='exe_file',
        ),
        migrations.AlterField(
            model_name='app',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TemporaryLink',
        ),
    ]
