# Generated by Django 6.0.3 on 2026-05-20 12:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_app_apk_file_remove_app_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='examyear',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Sawirka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Sawirka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Muuqaalka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Muuqaalka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Muuqaal Loop ah)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Muuqaal Loop ah)'),
        ),
    ]
