# Generated by Django 6.0.3 on 2026-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_chatmessage_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/images/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/videos/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='readings/images/'),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='readings/videos/'),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
