# Generated by Django 6.0.3 on 2026-05-20 13:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_quizquestion_image_file_quizquestion_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Xogta Maqaalka'),
        ),
        migrations.AlterField(
            model_name='globalnotice',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Faahfaahinta Qoraalka'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Faahfaahinta Qoraalka'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Nuxurka Casharka'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Farriinta Dayactirka'),
        ),
    ]
