# Generated by Django 6.0.3 on 2026-05-20 14:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_content_body_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examyear',
            options={},
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='is_portrait',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='is_portrait',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalnotice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Faahfaahinta Qoraalka'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='message',
            field=models.TextField(default='Horumarin ayaa socota...'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_file',
            field=models.ImageField(blank=True, help_text='Soo geli sawirka gadaal uga muuqanaya interface-ka dhalada ah.', null=True, upload_to=core.models.get_upload_path, verbose_name='Sawirka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_url',
            field=models.URLField(blank=True, help_text='Haddii aad sawirka ka keenayso internet-ka, halkan geli link-giisa.', null=True, verbose_name='Sawirka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_file',
            field=models.FileField(blank=True, help_text='Soo geli muuqaal (MP4) oo dhabar-ka gadaal uga dagi lahaa interface-ka.', null=True, upload_to=core.models.get_upload_path, verbose_name='Muuqaalka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_url',
            field=models.URLField(blank=True, help_text='Haddii aad muuqaalka ka keenayso internet-ka, halkan geli link-giisa (MP4 format).', null=True, verbose_name='Muuqaalka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_image',
            field=models.ImageField(blank=True, help_text='Sawirka rasmiga ah ee goobada ugu muuqanaya Faiza.', null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_video',
            field=models.FileField(blank=True, help_text='Haddii aad rabto muuqaal clip ah (MP4) oo goobada gudaheed dhex dhasha.', null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Muuqaal Loop ah)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_image',
            field=models.ImageField(blank=True, help_text='Sawirka rasmiga ah ee goobada ugu muuqanaya Maxamed.', null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_video',
            field=models.FileField(blank=True, help_text='Haddii aad rabto muuqaal clip ah (MP4) oo goobada gudaheed dhex dhasha.', null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Muuqaal Loop ah)'),
        ),
    ]
