# Generated by Django 6.0.3 on 2026-05-20 21:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_chatmessage_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='maintenance/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='maintenance/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_portrait', models.BooleanField(default=False, help_text='Gali calaamad haddii sawirka/video-gu yahay mid taagan')),
            ],
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Sawirka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Sawirka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Muuqaalka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Muuqaalka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Muuqaal Loop ah)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Muuqaal Loop ah)'),
        ),
    ]
