# Generated by Django 6.0.3 on 2026-05-20 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_maintenancesetting_alter_ttssetting_bg_image_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Habaynta Bogga Chat-ka', max_length=100)),
                ('bg_image_file', models.ImageField(blank=True, null=True, upload_to='chat_bg_images/', verbose_name='Sawirka Gadaal (File)')),
                ('bg_image_url', models.URLField(blank=True, null=True, verbose_name='Sawirka Gadaal (Link/URL)')),
                ('bg_video_file', models.FileField(blank=True, null=True, upload_to='chat_bg_videos/', verbose_name='Muuqaalka Gadaal (File)')),
                ('bg_video_url', models.URLField(blank=True, null=True, verbose_name='Muuqaalka Gadaal (Link/URL)')),
                ('is_video_muted', models.BooleanField(default=True, verbose_name="Muuqaalka Cod la'aan ha ahaado (Muted)?")),
            ],
            options={
                'verbose_name': 'Habaynta Chat-ka',
                'verbose_name_plural': 'Habaynta Chat-ka',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Fariinta Chat-ka', 'verbose_name_plural': 'Fariimaha Chat-ka'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/', verbose_name='Faylka La Soo Raaciyay'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/', verbose_name='Sawirka la diray'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_folder',
            field=models.BooleanField(default=False, verbose_name='Ma yahay Folder (Zip/Rar)?'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Fariinta'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Qofka Loo Diray'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Qofka Diray'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waqtiga La Diray'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat/voices/', verbose_name='Codka la diray'),
        ),
    ]
