# Generated by Django 6.0.3 on 2026-05-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_chatsetting_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsetting',
            name='bg_type',
            field=models.CharField(choices=[('image', 'Sawir (Image)'), ('video', 'Muuqaal (Video)')], default='image', max_length=10, verbose_name='Nooca Background-ka'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='bg_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='chat_bg/', verbose_name='Sawirka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='bg_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Sawirka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='bg_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Muuqaalka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='is_video_muted',
            field=models.BooleanField(default=True, verbose_name='Mute Muuqaalka'),
        ),
        migrations.AlterField(
            model_name='chatsetting',
            name='title',
            field=models.CharField(default='MUCJISADA Chat Settings', max_length=100),
        ),
    ]
