# Generated by Django 6.0.3 on 2026-05-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_chatsetting_bg_type_alter_chatsetting_bg_image_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceSetting',
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_portrait',
            field=models.BooleanField(default=False, verbose_name='Ma Muuqaal Taagan Baa (Portrait)?'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='Soo geli Sawir (File)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='message',
            field=models.TextField(blank=True, default='Horumarin ayaa socota...', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/', verbose_name='Soo geli Muuqaal (File)'),
        ),
    ]
