# Generated by Django 6.0.3 on 2026-05-21 14:09

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_delete_maintenancesetting_alter_sitesetting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatSetting',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ttssetting',
            options={},
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='is_portrait',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat/voices/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='settings/images/', verbose_name='Soo geli Sawir (File)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='message',
            field=models.TextField(default='Horumarin ayaa socota...'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='settings/videos/', verbose_name='Soo geli Muuqaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_file',
            field=models.ImageField(blank=True, help_text='Soo geli sawirka gadaal uga muuqanaya interface-ka dhalada ah.', null=True, upload_to=core.models.get_upload_path, verbose_name='Sawirka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_image_url',
            field=models.URLField(blank=True, help_text='Haddii aad sawirka ka keenayso internet-ka, halkan geli link-giisa.', null=True, verbose_name='Sawirka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_file',
            field=models.FileField(blank=True, help_text='Soo geli muuqaal (MP4) oo dhabar-ka gadaal uga dagi lahaa interface-ka.', null=True, upload_to=core.models.get_upload_path, verbose_name='Muuqaalka Gadaal (File)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='bg_video_url',
            field=models.URLField(blank=True, help_text='Haddii aad muuqaalka ka keenayso internet-ka, halkan geli link-giisa (MP4 format).', null=True, verbose_name='Muuqaalka Gadaal (URL Link)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_image',
            field=models.ImageField(blank=True, help_text='Sawirka rasmiga ah ee goobada ugu muuqanaya Faiza.', null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='faiza_avatar_video',
            field=models.FileField(blank=True, help_text='Haddii aad rabto muuqaal clip ah (MP4) oo goobada gudaheed dhex dhasha.', null=True, upload_to=core.models.get_upload_path, verbose_name='Faiza Avatar (Muuqaal Loop ah)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_image',
            field=models.ImageField(blank=True, help_text='Sawirka rasmiga ah ee goobada ugu muuqanaya Maxamed.', null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Sawir)'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='maxamed_avatar_video',
            field=models.FileField(blank=True, help_text='Haddii aad rabto muuqaal clip ah (MP4) oo goobada gudaheed dhex dhasha.', null=True, upload_to=core.models.get_upload_path, verbose_name='Maxamed Avatar (Muuqaal Loop ah)'),
        ),
    ]
