# Generated by Django 6.0.3 on 2026-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_delete_chatsetting_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_type', models.CharField(choices=[('none', 'Madow'), ('image', 'Sawir'), ('video', 'Muuqaal')], default='none', max_length=10)),
                ('bg_url', models.URLField(blank=True, help_text='Haddii aad URL isticmaalayso', null=True)),
                ('bg_file', models.FileField(blank=True, help_text='Haddii aad File ka soo upload-garaynayso', null=True, upload_to='chat_bg/')),
                ('announcement_text', models.CharField(blank=True, help_text='Digniinta cas ee kore ka ordaysa', max_length=255, null=True)),
                ('show_chat_ad', models.BooleanField(default=False)),
                ('chat_ad_text', models.TextField(blank=True, null=True)),
                ('chat_ad_media_url', models.URLField(blank=True, null=True)),
                ('chat_ad_media_file', models.ImageField(blank=True, null=True, upload_to='chat_ads/')),
            ],
        ),
    ]
