# Generated by Django 6.0.3 on 2026-05-21 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_adminchatsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/images/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/videos/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='readings/images/'),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='readings/videos/'),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, db_table='user_profile_friends_map', related_name='profile_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
