# Generated by Django 6.0.3 on 2026-05-21 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_quizquestion_image_file_quizquestion_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminChatSettings',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='is_portrait',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='is_portrait',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='readingmaterial',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, db_table='user_profile_friends_map', related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
