# Generated by Django 6.0.3 on 2026-05-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_delete_adminchatsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBackgroundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Qaabkaynta Bogga Chat-ka', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Haddii aad rabto in naqshaddaan ay hadda shaqayso calaamadi.')),
                ('main_bg_type', models.CharField(choices=[('color', 'Midab Caadi ah (Solid Color)'), ('image_file', 'Sawir (Fayl ahaan u soo geli)'), ('image_url', 'Sawir (Link/URL ahaan u geli)'), ('video_file', 'Muuqaal (Fayl ahaan u soo geli)'), ('video_url', 'Muuqaal (Link/URL ahaan u geli)'), ('announcement', 'Qoraal Ogeysiis ah oo keliya')], default='color', max_length=20)),
                ('main_bg_color', models.CharField(default='#020617', help_text='Tusaale: #020617 ama rgba(2, 6, 23, 1)', max_length=20)),
                ('main_bg_file', models.FileField(blank=True, help_text='Soo geli sawir ama muuqaal MP4 ah', null=True, upload_to='chat_backgrounds/')),
                ('main_bg_url', models.URLField(blank=True, help_text='Haddii aad link dibadda ah ka keenayso sawirka ama muuqaalka', null=True)),
                ('main_announcement_text', models.TextField(blank=True, help_text='Qoraal digniin ama wargelin ah oo ka muuqanaya background-ka weyn', null=True)),
                ('box_bg_type', models.CharField(choices=[('color', 'Midab Caadi ah (Solid Color)'), ('image_file', 'Sawir (Fayl ahaan u soo geli)'), ('image_url', 'Sawir (Link/URL ahaan u geli)'), ('video_file', 'Muuqaal (Fayl ahaan u soo geli)'), ('video_url', 'Muuqaal (Link/URL ahaan u geli)'), ('announcement', 'Qoraal Ogeysiis ah oo keliya')], default='color', max_length=20)),
                ('box_bg_color', models.CharField(default='rgba(15, 23, 42, 0.7)', help_text='Muraayad ka dhig: rgba(15, 23, 42, 0.7)', max_length=20)),
                ('box_bg_file', models.FileField(blank=True, help_text='Soo geli sawir ama muuqaal sanduuqa dhexdiisa ah', null=True, upload_to='chat_box_backgrounds/')),
                ('box_bg_url', models.URLField(blank=True, help_text='Link-ga sawirka ama muuqaalka sanduuqa dhexdiisa', null=True)),
                ('box_overlay_text', models.CharField(blank=True, help_text='Qoraal khafiif ah oo dhex fadhiya sanduuqa fariimaha', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Chat Background Setting',
                'verbose_name_plural': 'Chat Background Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='video_content',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='max_characters',
            field=models.PositiveIntegerField(default=1000, help_text='Tirada ugu bayan ee xarfaha qofku qori karo hal mar.'),
        ),
    ]
