# Generated by Django 6.0.3 on 2026-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_chatbackgroundsettings_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBackgroundSettings',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='video_content',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/'),
        ),
        migrations.AlterField(
            model_name='ttssetting',
            name='max_characters',
            field=models.PositiveIntegerField(default=1000, help_text='Tirada ugu badan ee xarfaha qofku qori karo hal mar.'),
        ),
    ]
