# Generated by Django 6.0.3 on 2026-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_delete_chatbackgroundsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBackgroundControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tusaale: Xayaysiis, Digniin, ama Magaca Background-ka', max_length=150)),
                ('media_type', models.CharField(choices=[('image', 'Sawir (Image)'), ('video', 'Muuqaal (Video)')], default='image', max_length=10)),
                ('source_type', models.CharField(choices=[('url', 'Xiriiriye (URL Link)'), ('file', 'Soo geli File (Upload File)')], default='url', max_length=10)),
                ('media_url', models.URLField(blank=True, help_text='Haddii aad dooratay URL, halkan geli link-iga', null=True)),
                ('media_file', models.FileField(blank=True, help_text='Haddii aad dooratay File, halkan ka soo upload garee', null=True, upload_to='admin_backgrounds/')),
                ('is_active', models.BooleanField(default=False, help_text='Haddii aad tick- garayso, kani wuxuu noqonayaa background-ka hadda ka muuqda chat-ka isticmaalayaasha')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
