# Generated by Django 6.0.3 on 2026-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_adminbackgroundcontrol_alter_chatmessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ciwaanka')),
                ('media_type', models.CharField(choices=[('image', 'Sawir (Image)'), ('video', 'Muuqaal (Video)')], default='image', max_length=10)),
                ('bg_image_file', models.ImageField(blank=True, null=True, upload_to='chat_bg/images/')),
                ('bg_video_file', models.FileField(blank=True, null=True, upload_to='chat_bg/videos/')),
                ('bg_image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('bg_video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Muuqaalka miyuu shaqaynayaa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
