# Generated by Django 6.0.3 on 2026-05-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_dynamicbackground'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminBackgroundControl',
        ),
        migrations.DeleteModel(
            name='DynamicBackground',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
