# Generated by Django 6.0.3 on 2026-05-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ciwaanka Ogeysiiska/Xayeysiiska')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Faahfaahinta Qoraalka')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='notices/images/', verbose_name='Soo geli Sawir (File)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Sawir Link ah (URL)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='notices/videos/', verbose_name='Soo geli Muuqaal (File)')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Muuqaal Link ah (URL - YouTube)')),
                ('is_portrait', models.BooleanField(default=False, verbose_name='Muuqaalku ma taagan yahay? (Shorts/TikTok size)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Muu muuqanayaa App-ka? (Active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Notice & Ad',
                'verbose_name_plural': 'Global Notices & Ads',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_emoji', models.CharField(blank=True, default='📚', max_length=50, null=True)),
                ('icon_image_file', models.ImageField(blank=True, null=True, upload_to='subject_icons/images/')),
                ('icon_image_url', models.URLField(blank=True, help_text='Link-ga sawirka icon-ka', max_length=500, null=True)),
                ('icon_video_file', models.FileField(blank=True, null=True, upload_to='subject_icons/videos/')),
                ('icon_video_url', models.URLField(blank=True, help_text='Link-ga muuqaalka icon-ka', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct_option_index', models.IntegerField(help_text='Geli 0 haddii option1 sax yahay, 1 haddii option2...')),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='banaadir.examyear')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='banaadir.examyear')),
            ],
        ),
        migrations.AddField(
            model_name='examyear',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='banaadir.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='examyear',
            unique_together={('subject', 'year')},
        ),
    ]
