# Generated by Django 6.0.3 on 2026-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='homepage/images/')),
                ('image_url', models.URLField(blank=True, help_text='Link-ga sawirka', null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='homepage/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Link-ga muuqaalka (YouTube/Vimeo)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage Contents',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('message', models.TextField(default='Horumarin ayaa socota...')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='settings/images/', verbose_name='Soo geli Sawir (File)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Sawir Link ah (URL)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='settings/videos/', verbose_name='Soo geli Muuqaal (File)')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Muuqaal Link ah (URL)')),
            ],
        ),
    ]
