# Generated by Django 6.0.3 on 2026-05-28 12:30

import tts_interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TTS Global Settings', max_length=100)),
                ('max_characters', models.PositiveIntegerField(default=1000, help_text='Tirada ugu badan ee xarfaha qofku qori karo hal mar.')),
                ('bg_image_file', models.ImageField(blank=True, null=True, upload_to=tts_interface.models.get_upload_path, verbose_name='Sawirka Gadaal (File)')),
                ('bg_image_url', models.URLField(blank=True, null=True, verbose_name='Sawirka Gadaal (URL Link)')),
                ('bg_video_file', models.FileField(blank=True, null=True, upload_to=tts_interface.models.get_upload_path, verbose_name='Muuqaalka Gadaal (File)')),
                ('bg_video_url', models.URLField(blank=True, null=True, verbose_name='Muuqaalka Gadaal (URL Link)')),
                ('faiza_avatar_image', models.ImageField(blank=True, null=True, upload_to=tts_interface.models.get_upload_path, verbose_name='Faiza Avatar (Sawir)')),
                ('faiza_avatar_video', models.FileField(blank=True, null=True, upload_to=tts_interface.models.get_upload_path, verbose_name='Faiza Avatar (Muuqaal Loop ah)')),
                ('maxamed_avatar_image', models.ImageField(blank=True, null=True, upload_to=tts_interface.models.get_upload_path, verbose_name='Maxamed Avatar (Sawir)')),
                ('maxamed_avatar_video', models.FileField(blank=True, null=True, upload_to=tts_interface.models.get_upload_path, verbose_name='Maxamed Avatar (Muuqaal Loop ah)')),
            ],
        ),
    ]
