# Generated by Django 6.0.3 on 2026-05-28 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='app_icons/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('html_code', models.TextField(blank=True, default='<h1>Ku soo dhawaaw App-kayga</h1>', null=True)),
                ('css_code', models.TextField(blank=True, default='body { background-color: white; text-align: center; font-family: sans-serif; }', null=True)),
                ('js_code', models.TextField(blank=True, default="console.log('App-ka waa diyaar!');", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
