# Generated by Django 6.0.3 on 2026-05-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_html', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Cinwaanka')),
                ('content', models.TextField(blank=True, verbose_name='Qoraalka Note-ka')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='keep_notes_files/', verbose_name='Faylka Lifaaqa ah')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Wakhtiga la abuuray')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Wakhtiga la cusboonaysiiyay')),
                ('device_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aaladda laga soo qoray')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='profile_html.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
