# Generated by Django 6.0.3 on 2026-05-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_notes', '0001_initial'),
        ('profile_html', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Sugaya'), ('accepted', 'La Aqbalay'), ('rejected', 'La Diiday')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='profile_html.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='profile_html.userprofile')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='KeepNotesUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_mode', models.CharField(choices=[('storage', 'Kaydin (Google Drive Mode)'), ('transfer', 'Kala-gudbin Kaliya (Transfer Mode)')], default='transfer', max_length=20)),
                ('allowed_storage_gb', models.FloatField(default=0.0)),
                ('used_storage_mb', models.FloatField(default=0.0)),
                ('remaining_transfer_seconds', models.IntegerField(default=7200)),
                ('last_active_time', models.DateTimeField(blank=True, null=True)),
                ('is_timer_running', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keep_notes_settings', to='profile_html.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('amount_usd', models.FloatField()),
                ('sender_phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Sugaya Hubinta Admin'), ('approved', 'La Anbabixiyey')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_html.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SharedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text_content', models.TextField(blank=True)),
                ('is_code', models.BooleanField(default=False)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='keep_notes/shared_files/')),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size_mb', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_received', to='profile_html.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_sent', to='profile_html.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
