# Generated by Django 6.0.3 on 2026-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_notes', '0003_remove_keepnotesusersetting_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='keep_notes/images/', verbose_name='Sawir'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('text', 'Qoraal Caadi'), ('code', 'Code Snippet'), ('link', 'Link/URL')], default='text', max_length=20, verbose_name='Nooca Note-ka'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, verbose_name='Qoraalka'),
        ),
        migrations.AlterField(
            model_name='note',
            name='device_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aaladda'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='keep_notes/files/', verbose_name='Faylka (PDF/Doc)'),
        ),
    ]
