# Generated by Django 6.0.3 on 2026-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_notes', '0004_note_image_note_note_type_alter_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='code_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Luuqadda Code-ka'),
        ),
        migrations.AddField(
            model_name='note',
            name='detected_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='detected_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='keep_notes/videos/', verbose_name='Muuqaalka'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, verbose_name='Qoraalka Note-ka'),
        ),
        migrations.AlterField(
            model_name='note',
            name='device_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aaladda laga soo qoray'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='keep_notes/files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='keep_notes/images/', verbose_name='Sawirka'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('text', 'Qoraal Caadi ah'), ('code', 'Code Snippet'), ('link', 'Link/URL'), ('phone', 'Phone Number'), ('image', 'Sawir'), ('video', 'Muuqaal'), ('file', 'File')], default='text', max_length=20, verbose_name='Nooca Note-ka'),
        ),
    ]
