# Generated by Django 6.0.3 on 2026-05-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keep_notes', '0005_note_code_language_note_detected_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='code_language',
        ),
        migrations.RemoveField(
            model_name='note',
            name='detected_link',
        ),
        migrations.RemoveField(
            model_name='note',
            name='detected_phone',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_type',
        ),
        migrations.RemoveField(
            model_name='note',
            name='video',
        ),
        migrations.AlterField(
            model_name='note',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='keep_notes_files/', verbose_name='Faylka Lifaaqa ah'),
        ),
    ]
