# Generated by Django 6.0.3 on 2026-06-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_window', '0002_chatmessage_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted_by_receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted_by_sender',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_edited',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
