# Generated by Django 6.0.3 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxamed_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, help_text='Ama halkan ku qor URL-ka tooska ah ee sawirka', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='video_file',
            field=models.FileField(blank=True, help_text='Soo geli muuqaal gaar ah (MP4 format) (File)', null=True, upload_to='game_videos/'),
        ),
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ama halkan ku qor URL-ka tooska ah ee muuqaalka', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, help_text='Soo geli sawirka icon-ka ah ee ciyaarta (File)', null=True, upload_to='game_icons/'),
        ),
    ]
