# Generated by Django 6.0.3 on 2026-05-22 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, unique=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('secret_password', models.CharField(max_length=100)),
                ('subscription_years', models.IntegerField(default=1)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('payment_method', models.CharField(choices=[('evc_plus', 'EVC Plus'), ('edahab', 'eDahab')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('tarbiyo', models.CharField(default='D-', max_length=5)),
                ('carabi', models.CharField(default='D-', max_length=5)),
                ('af_soomaali', models.CharField(default='D-', max_length=5)),
                ('xisaab', models.CharField(default='D-', max_length=5)),
                ('cilmi_bulsho', models.CharField(default='D-', max_length=5)),
                ('saynis', models.CharField(default='D-', max_length=5)),
                ('ingiriisi', models.CharField(default='D-', max_length=5)),
                ('teknooloji', models.CharField(default='D-', max_length=5)),
                ('celceliska', models.CharField(default='D-', max_length=10)),
                ('goaan', models.CharField(default='Gudbay', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exam_app.schoolprofile')),
            ],
        ),
    ]
