# Generated by Django 6.0.3 on 2026-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='sender_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
