# Generated by Django 6.0.3 on 2026-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_schoolprofile_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='biology',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='business',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='chemistry',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='juqraafi',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='physics',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='school_level',
            field=models.CharField(choices=[('dhexe', 'Dugsi Dhexe (8 Maado)'), ('sare', 'Dugsi Sare (12 Maado)')], default='dhexe', max_length=10),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='taariikh',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='celceliska',
            field=models.CharField(default='D-', max_length=5),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='cilmi_bulsho',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='goaan',
            field=models.CharField(default='Gudbay', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='saynis',
            field=models.CharField(blank=True, default='D-', max_length=5, null=True),
        ),
    ]
