# Generated by Django 6.0.3 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_html', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='profiles/videos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
